# Generated by Django 3.2.19 on 2023-07-11 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_image', models.ImageField(blank=True, null=True, upload_to='categorie')),
                ('categorie_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('time', models.TimeField(blank=True, max_length=100, null=True)),
                ('publish_date', models.DateField(blank=True, max_length=255, null=True)),
                ('img_alttag', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_image', models.ImageField(blank=True, null=True, upload_to='templates_images')),
                ('template_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template_discription', models.TextField(blank=True, default='', null=True)),
                ('template_status', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('template_time', models.TimeField(blank=True, max_length=100, null=True)),
                ('template_publish_date', models.DateField(blank=True, max_length=255, null=True)),
                ('template_img_alttag', models.TextField(blank=True, default='', null=True)),
                ('template_price', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('template_rating', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('video_file', models.FileField(upload_to='tempvideo/')),
                ('categori_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Theme.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_image', models.ImageField(blank=True, null=True, upload_to='categorie')),
                ('u_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('u_desig', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('u_password', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('u_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
