# Generated by Django 3.2.19 on 2023-07-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0002_auto_20230713_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_data',
            name='u_username',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admin_data',
            name='u_password',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
