# Generated by Django 3.2.20 on 2023-07-28 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0003_auto_20230714_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='template_code',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='templates',
            name='template_status',
            field=models.CharField(blank=True, default='ALTS000', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_filename', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('zip_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('temp_code', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Theme.templates')),
            ],
        ),
    ]
