# Generated by Django 3.2.20 on 2023-07-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0004_auto_20230728_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='temp_devname',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
