# Generated by Django 3.2.20 on 2023-10-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0006_categorie_details_categorie_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enq_date', models.DateField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('company', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.BooleanField(default=0)),
            ],
        ),
    ]
